### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'canProduce') videosdk.js:2

### ISSUE THREAD

**Issue by yendiDev** [videosdk-live/videosdk-docs#91]
I followed the docs at: https://docs.videosdk.live/react/guide/video-and-audio-calling-api-sdk/quick-start

I am working with reactjs. I found it extremely complicated and less organised to read your documentation, and after carefully following your docs and watching your tutorial on youtube (which is very different from what you have in the docs), I still am not able to start a meeting. I get the auth token and all, but when I click "toggleWebcam", the error appears. 

Please provide help to fix the above issue. 

see screenshot: 
![image](https://user-images.githubusercontent.com/57093800/221448999-64a8c6e3-f100-4820-a702-87fd69b9f8bf.png)

**Comment by ahmedbhesaniya97** [comment]
Hello @yendiDev 👋, 
I'm Ahmed Bhesaniya.
At VideoSDK, I serve as Tech Lead.
First of all, I want to thank you for bringing up this topic. We are very grateful for that.
Is it possible to discuss all the documentation or SDK feedback for the product over the one to one meeting ?
It will help us to improve the product and serves you better.
I look forward to hearing from you.

Thank you.

**Comment by yendiDev** [comment]
Yes, that will be fine.

**Comment by ahmedbhesaniya97** [comment]
@yendiDev 
Let's have a call as per your schedule.
Link to book a call : https://bookings.videosdk.live/#/customer/videosdk

**Comment by yendiDev** [comment]
ok.
how do I call the toggleCamera method  after the onMeetingJoined() event is
called?

**Comment by ahmedbhesaniya97** [comment]
@yendiDev 
Let me provide you simple example.
```js
import {
  useMeeting,
} from "@videosdk.live/react-native-sdk";
import { useEffect, useState } from "react";
import React from "react";

export default function MeetingContainer({ webcamEnabled, meetingType }) {
  const [isJoined, setJoined] = useState(false);

  const { join, toggleWebcam, leave } = useMeeting({
    onMeetingJoined: () => {
      setTimeout(() => {
        setJoined(true);
      }, 500);
    },
  });

  useEffect(() => {
    setTimeout(() => {
      if (!isJoined) {
        join();
        if (webcamEnabled) toggleWebcam();
      }
    }, 1000);
  }, []);

  return isJoined ? <YourMeetingComponent /> : <WaitingScreenComponent />;
}


```

**Comment by yendiDev** [comment]
Thanks, I'll check it out and give you feedback.

**Comment by yendiDev** [comment]
still no success. Can we jump on a call real quick so you show me how to
fix it?

**Comment by ahmedbhesaniya97** [comment]
Sure @yendiDev

**Comment by ahmedbhesaniya97** [comment]
Do you use Discord ?

**Comment by yendiDev** [comment]
Great, thanks!

https://meet.google.com/moj-gjzy-wfu

Meeting has started. Won't take long

**Comment by yendiDev** [comment]
Yes, I do.

**Comment by ahmedbhesaniya97** [comment]
username ?

**Comment by yendiDev** [comment]
cratr-mongo
